apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-backend
  labels:
    app: url-shortener-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-backend
  template:
    metadata:
      labels:
        app: url-shortener-backend
    spec:
      containers:
        - name: backend
          image: <IMAGE_BACKEND>
          ports:
            - containerPort: 3333
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REFRESH_SECRET
            - name: CORS_ORIGIN
              value: "*"
            - name: ENABLE_METRICS
              value: "true"
            - name: ENABLE_TRACING
              value: "false"
            - name: OTEL_SERVICE_NAME
              value: "url-shortener-backend"
            - name: JAEGER_ENDPOINT
              value: "http://jaeger:14268/api/traces"
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-backend
spec:
  selector:
    app: url-shortener-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333 