apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://urlshortener:senha@postgres:5432/urlshortener"
  JWT_SECRET: "changeme"
  REFRESH_SECRET: "changeme" 