apiVersion: v1
kind: ConfigMap
metadata:
  name: krakend-config
  labels:
    app: krakend
  # O conteúdo do krakend.json deve ser colado aqui
  # Exemplo:
data:
  krakend.json: |
    {
      "version": 2,
      "name": "Krakend API Gateway",
      "port": 8080,
      "endpoints": [],
      "extra_config": {}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          image: devopsfaith/krakend:2.5.2
          args:
            - "run"
            - "-c"
            - "/etc/krakend/krakend.json"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config
---
apiVersion: v1
kind: Service
metadata:
  name: krakend
spec:
  selector:
    app: krakend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 