name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, iam]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: |
          if [ -f eslint.config.mjs ]; then npx eslint .; fi

      - name: Build (se aplicável)
        run: |
          if [ -f tsconfig.json ]; then npm run build; fi

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ matrix.service }}/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Testes (backend apenas)
        if: matrix.service == 'backend'
        run: npm test 
      - name: Upload coverage to Codecov
        if: matrix.service == 'backend'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Testes (iam apenas)
        if: matrix.service == 'iam'
        run: npm test 